import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import Box from "../components/Box.ts";
import { createRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const canvasRef = createRef<HTMLCanvasElement>();
  return (
    <>
      <Head>
        <title>Hyvää Joulua!</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Canvas className={styles.canvas} ref={canvasRef}>
          <ambientLight intensity={0.5} />
          <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
          <pointLight position={[-10, -10, -10]} />
          <Box position={[-1.2, 0, 0]} />
          <Box position={[1.2, 0, 0]} />
        </Canvas>
      </main>
    </>
  );
}
