import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { createRef } from "react";
import Ornament from "../components/Ornament";
import Floor from "../components/Floor";
import { OrbitControls, PerspectiveCamera } from "@react-three/drei";
import SkyBox from "../components/SkyBox";
import { Color } from "three";

export default function Home() {
  const canvasRef = createRef<HTMLCanvasElement>();
  return (
    <>
      <Head>
        <title>Hyvää Joulua!</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Canvas className={styles.canvas} ref={canvasRef}>
          <ambientLight intensity={0.5} />
          <pointLight position={[-10, -10, -10]} />
          <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
          <Ornament color={new Color("hotpink")} position={[1, 1, 0]} />
          <Ornament
            color={new Color("red")}
            scale={[1, 1, 1]}
            position={[-2, 1, 0]}
          />

          <SkyBox />
          <Floor
            position={[0, -10, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[200, 200, 200]}
          />
          <PerspectiveCamera position={[50, 20, 20]} makeDefault />
          <OrbitControls maxPolarAngle={Math.PI / 2} />
        </Canvas>
      </main>
    </>
  );
}
