import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { createRef, useState } from "react";
import Floor from "../components/Floor";
import { OrbitControls, PerspectiveCamera } from "@react-three/drei";
import SkyBox from "../components/SkyBox";
import { Color } from "three";
import { useRouter } from "next/router";
import { useKeyboard } from "../hooks/useKeyboard";
import Ornaments from "../components/Ornaments";
import * as THREE from "three";
export default function Home() {
  const canvasRef = createRef<HTMLCanvasElement>();
  const router = useRouter();
  const { autorotate, edit } = router.query;
  const [rotate, setRotate] = useState<boolean>(autorotate === "true");
  const [editMode, setEditMode] = useState<boolean>(edit === "true");
  useKeyboard([
    [
      "Enter",
      (e) => {
        setRotate((old) => !old);
      },
    ],
    [
      "Space",
      (e) => {
        setEditMode((old) => !old);
      },
    ],
  ]);

  return (
    <>
      <Head>
        <title>Hyvää Joulua!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Canvas className={styles.canvas} ref={canvasRef}>
          <ambientLight intensity={0.5} />
          <pointLight position={[-10, -10, -10]} />
          <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
          <Ornaments
            edit={editMode}
            initialOrnaments={[
              {
                color: new Color("hotpink"),
                position: new THREE.Vector3(1, 1, 0),
                roughness: 0.4,
                transparent: true,
                opacity: 0.7,
              },
              {
                color: new Color("red"),
                scale: [1, 1, 1],
                position: new THREE.Vector3(-2, 1, 0),
              },
              {
                color: new Color("blue"),
                scale: [2, 2, 2],
                position: new THREE.Vector3(5, 5, 2),
                roughness: 0.4,
                transparent: true,
                opacity: 0.7,
              },
            ]}
          />

          <SkyBox />
          <Floor
            position={[0, -10, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[200, 200, 200]}
          />
          <PerspectiveCamera position={[50, 20, 20]} makeDefault />
          <OrbitControls maxPolarAngle={Math.PI / 2} autoRotate={rotate} />
        </Canvas>
      </main>
    </>
  );
}
